"""add habit frequency

Revision ID: 40b641c4edc4
Revises: 5c6732131c53
Create Date: 2026-09-22 11:47:18.940015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b641c4edc4'
down_revision = '5c6732131c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'habits',
    sa.Column(
        'frequency',
        sa.String(),
        nullable=False,
        server_default='daily'
    )
)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'frequency')
    # ### end Alembic commands ###
