"""Add habit created timestamp

Revision ID: 5c6732131c53
Revises: ff38c1eacba1
Create Date: 2026-09-22 09:27:31.454803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6732131c53'
down_revision = 'ff38c1eacba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'created_at')
    # ### end Alembic commands ###
