"""Prevent duplicate habit completions

Revision ID: ff38c1eacba1
Revises: 471f00b782c2
Create Date: 2026-09-17 14:44:00.889170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff38c1eacba1'
down_revision = '471f00b782c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_habit_completion_date', 'habit_completions', ['habit_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_habit_completion_date', 'habit_completions', type_='unique')
    # ### end Alembic commands ###
